# Site settings
title: My Blog
email: troy@avidbrain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog written by someone who probably won't keep up with it and generally
  does not enjoy writing out his thoughts. Happy reading!
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: troym9731
github_username:  troym9731

# Build settings
markdown: kramdown
